### ISSUE TITLE
Integrate with FuseSoC and Edalize

### ISSUE THREAD

**Issue by taichi-ishitani** [pezy-computing/flgen#13]
This is an feedback from @olofk.

![image](https://user-images.githubusercontent.com/2922232/210678769-4edf98e4-7ae4-4011-a459-091fa3413b5f.png)

**Comment by taichi-ishitani** [comment]
I think FLGen can output `file` and `tool-options` fields of EDMA.

* https://edalize.readthedocs.io/en/latest/edam/api.html#file
* https://edalize.readthedocs.io/en/latest/edam/api.html#tool-options

How can I export macro definitions and include direcotries? Using `tool-options`?

**Comment by taichi-ishitani** [comment]
> How can I export macro definitions and include direcotries? Using tool-options?

@olofk,
Do you have any proposal?

**Comment by olofk** [comment]
Here is an example of and EDAM file that FuseSoC has produced for Servant, the reference platform for the SERV CPU. Many of these fields are optional so you don't need to care about them, but you can see an example of how e.g. parameters work

```
dependencies:
  ::serv:1.2.1: []
  ::servant:1.2.1:
  - ::serv:1.2.1
files:
- core: ::serv:1.2.1
  file_type: vlt
  name: src/serv_1.2.1/data/verilator_waiver.vlt
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_bufreg.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_bufreg2.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_alu.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_csr.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_ctrl.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_decode.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_immdec.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_mem_if.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_rf_if.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_rf_ram_if.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_rf_ram.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_state.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_top.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_rf_top.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_aligner.v
- core: ::serv:1.2.1
  file_type: verilogSource
  name: src/serv_1.2.1/rtl/serv_compdec.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/servant/servant_clock_gen.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/servant/servant_timer.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/servant/servant_gpio.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/servant/servant_arbiter.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/servant/servant_mux.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/servant/servant_ram.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/servant/servant.v
- core: ::servant:1.2.1
  file_type: verilogSource
  name: src/servant_1.2.1/bench/servant_sim.v
- core: ::servant:1.2.1
  file_type: cppSource
  name: src/servant_1.2.1/bench/servant_tb.cpp
flow_options: {}
hooks: {}
name: servant_1.2.1
parameters:
  RISCV_FORMAL:
    datatype: bool
    paramtype: vlogdefine
  SERV_CLEAR_RAM:
    datatype: bool
    paramtype: vlogdefine
  align:
    datatype: int
    description: Enable/Disable the Misaligned access of instruction
    paramtype: vlogparam
  compressed:
    datatype: int
    description: Enable/Disable the Compressed extension
    paramtype: vlogparam
  firmware:
    datatype: file
    default: /home/olof/projects/serv/workspace/zephyr_phil_24.vh
    description: Preload RAM with a hex file at runtime (overrides memfile)
    paramtype: plusarg
  memsize:
    datatype: int
    default: 32768
    description: Memory size in bytes for RAM (default 8kiB)
    paramtype: vlogparam
  signature:
    datatype: file
    paramtype: plusarg
  timeout:
    datatype: int
    paramtype: plusarg
  uart_baudrate:
    datatype: int
    default: 55600
    description: Treat q output as an UART with the specified baudrate (0 or omitted
      parameter disables UART decoding)
    paramtype: plusarg
  vcd:
    datatype: bool
    paramtype: plusarg
  vcd_start:
    datatype: int
    description: Delay start of VCD dumping until the specified time
    paramtype: plusarg
  with_csr:
    datatype: int
    default: 1
    description: Enable/Disable CSR support
    paramtype: vlogparam
tool_options:
  verilator:
    verilator_options:
    - --trace
toplevel: servant_sim
version: 0.2.1
vpi: []
```
